config/routes.rb
Rails.application.routes.draw do

  resources :domains 
  resources :hosts

  get 'hosts/index'
  get 'domains/index'
  get 'home/index'

  root 'home#index'
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :hosts, :dependent => :delete_all
  validates :name, presence: true
end

app/models/host.rb
class Host < ActiveRecord::Base
  belongs_to :domain
  validates :hostname, presence: true, uniqueness: true
  validates :macaddress, presence: true, uniqueness: true, mac_address: true
  validates :ipaddress, presence: true, uniqueness: true, ip_address: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  def index
    @domains = Domain.all
  end

  def new
      @domain = Domain.new()
  end

  def edit
    @domain = Domain.find(params[:id])
  end

  def create
    @domain = Domain.new(domain_params)

    if @domain.save
      redirect_to domains_path
    else
      render 'new'
    end
  end

  def update
    @domain = Domain.find(params[:id])

    if @domain.update(domain_params)
      redirect_to domains_path
    else
      render 'edit'
    end
  end

  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    redirect_to domains_path
  end

  private
    def domain_params
        params.require(:domain).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
      @hosts = Host.all
  end

  def show
    @host = Host.find(params[:id])
  end

  def new
    redirect_to new_domain_path if !Domain.first
    @host = Host.new()
  end

  def edit
    @host = Host.find(params[:id])
  end

  def create
    @host = Host.new(host_params)

    if @host.save
      redirect_to @host
    else
      render 'new'
    end
  end

  def update
    @host = Host.find(params[:id])

    if @host.update(host_params)
      redirect_to @host
    else
      render 'edit'
    end
  end

  def destroy
    @host = Host.find(params[:id])
    @host.destroy

    redirect_to hosts_path
  end

  private
    def host_params
      params.require(:host).permit(:hostname, :macaddress, :ipaddress, :domain_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/domains/_form.html.haml
=form_for @domain, :html => { class: 'form-horizontal', role: 'form' } do |f|
  -if @domain.errors.any? 
    -@domain.errors.full_messages.each do |msg|
      %p{ class: 'alert alert-warning' }
        =msg
          
  .form-group
    =f.label :name, class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :name, class: 'form-control'
  .form-grop
    .col-sm-offset-2.cols-sm-10
      =f.submit 'Save', class: 'btn btn-default'
      =link_to 'Cancel', :back, { class: 'btn btn-default' }

app/views/domains/edit.html.haml
%h3 Edit domain

=render 'form'

app/views/domains/index.html.haml
%h3 Domains

- if @domains.count == 0
  %p.alert.alert-warning
    There's no domain registred yet.
- else
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th Domain
      %th
    - @domains.each do |domain|
      %tr{ class: cycle('odd', 'even') }
        %td= domain.name
        %td
          =link_to image_tag('edit.png', alt: 'Edit'), edit_domain_path(domain)
          =link_to image_tag('delete.png', alt: 'Delete'), domain_path(domain), method: :delete, data: { confirm: 'Are you sure?' }

app/views/domains/new.html.haml
%h3 New domain

=render 'form'

app/views/home/index.html.haml
.starter-template
  %h1 Pastry - Network Hosts Control

%p.lead
  This is a simple app to keep a list of hosts of a network.
  

app/views/hosts/_form.html.haml
=form_for @host, :html => { class: 'form-horizontal', role: 'form' } do |f|
  -if @host.errors.any? 
    -@host.errors.full_messages.each do |msg|
      %p{ class: 'alert alert-warning' }
        =msg
          
  .form-group
    =f.label :hostname, class: 'control-label col-sm-2'
    .col-sm-5
      =f.text_field :hostname, class: 'form-control'
    .col-sm-5
      =f.collection_select :domain_id, Domain.all, :id, :name, {}, { class: 'form-control' }
  .form-group
    =f.label :macaddress, class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :macaddress, class: 'form-control'
  .form-group
    =f.label :ipaddress, class: 'control-label col-sm-2'
    .col-sm-10
      =f.text_field :ipaddress, class: 'form-control'
  .form-grop
    .col-sm-offset-2.cols-sm-10
      =f.submit 'Save', class: 'btn btn-default'
      =link_to 'Cancel', :back, { class: 'btn btn-default' }

app/views/hosts/edit.html.haml
%h3 Edit host

=render 'form'

app/views/hosts/index.html.haml
%h3 Hosts

- if @hosts.count == 0
  %p.alert.alert-warning
    There's no host registred yet.
- else
  %table.table.table-striped.table-bordered.table-hover
    %tr
      %th Hostname
      %th Domain
      %th MAC address
      %th IP address
      %th
    - @hosts.each do |host|
      %tr{ class: cycle('odd','even') }
      %td= host.hostname
      %td= host.domain.name
      %td= host.macaddress
      %td= host.ipaddress
      %td
        =link_to image_tag('show.png', alt: 'Show'), host_path(host)
        =link_to image_tag('edit.png', alt: 'Edit'), edit_host_path(host)
        =link_to image_tag('delete.png', alt: 'Delete'), host_path(host), method: :delete, data: { confirm: 'Are you sure?' }

app/views/hosts/new.html.haml
%h3 New host

=render 'form'

app/views/hosts/show.html.haml
%h3 Show

%p
  The machine
  %strong
    =@host.hostname
  has the
  %strong
    =@host.ipaddress
  IP address configured on the NIC
  %strong
    =@host.macaddress
%p
  =link_to 'Back to host list', hosts_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pastry
    =csrf_meta_tags
    =stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =favicon_link_tag

  %body
    .navbar.navbar-inverse
      .container
        .navbar-header
          =link_to 'Pastry', root_path, class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-left
            %li.dropdown
              %a.dropdown-toggle{ data: { 'toggle': 'dropdown' } }
                Domains
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to 'List', domains_path
                %li
                  =link_to 'New', new_domain_path
            %li.dropdown
              %a.dropdown-toggle{ data: { 'toggle': 'dropdown' } } 
                Hosts
                %span.caret
              %ul.dropdown-menu
                %li
                  =link_to 'List', hosts_path
                %li
                  =link_to 'New', new_host_path
    .container
      =yield